// PDF Download Utility — uses a styled print window for clean PDF export
const PdfExport = {
  /**
   * Opens a new print-ready window with styled HTML content.
   * The user can then Save as PDF from the browser's print dialog.
   * @param {string} title - Document title
   * @param {string} bodyHtml - The HTML content to render
   */
  download(title, bodyHtml) {
    const win = window.open('', '_blank');
    if (!win) {
      alert('Please allow pop-ups to download the PDF.');
      return;
    }
    win.document.write(`<!DOCTYPE html>
<html>
<head>
  <title>${title} — RehabAI</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet">
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:'Inter',sans-serif; color:#1e293b; padding:40px; line-height:1.7; }
    .pdf-header { display:flex; justify-content:space-between; align-items:center; border-bottom:3px solid #6366f1; padding-bottom:16px; margin-bottom:28px; }
    .pdf-header h1 { font-size:22px; color:#6366f1; }
    .pdf-header .meta { font-size:12px; color:#64748b; text-align:right; }
    .pdf-section { margin-bottom:24px; }
    .pdf-section h2 { font-size:16px; color:#6366f1; border-bottom:1px solid #e2e8f0; padding-bottom:6px; margin-bottom:12px; }
    .pdf-section h3 { font-size:14px; color:#334155; margin-bottom:6px; }
    .pdf-row { display:flex; justify-content:space-between; padding:6px 0; border-bottom:1px solid #f1f5f9; font-size:13px; }
    .pdf-row .label { font-weight:600; color:#475569; min-width:140px; }
    .pdf-row .value { color:#1e293b; flex:1; }
    .pdf-badge { display:inline-block; padding:3px 10px; border-radius:12px; font-size:11px; font-weight:700; text-transform:uppercase; }
    .pdf-card { border:1px solid #e2e8f0; border-radius:10px; padding:16px; margin-bottom:14px; page-break-inside:avoid; }
    .pdf-card h4 { font-size:14px; margin-bottom:8px; color:#334155; }
    .pdf-card ul, .pdf-card ol { padding-left:20px; font-size:13px; }
    .pdf-card li { margin-bottom:4px; }
    .pdf-macros { display:flex; gap:12px; margin-top:8px; flex-wrap:wrap; }
    .pdf-macro { padding:4px 12px; border-radius:8px; font-size:12px; font-weight:600; background:#f1f5f9; }
    .pdf-footer { margin-top:32px; border-top:2px solid #e2e8f0; padding-top:12px; font-size:11px; color:#94a3b8; text-align:center; }
    .pdf-exercise { display:flex; gap:12px; align-items:flex-start; padding:10px 0; border-bottom:1px solid #f1f5f9; }
    .pdf-exercise:last-child { border-bottom:none; }
    .pdf-ex-num { width:28px; height:28px; border-radius:50%; background:#6366f1; color:#fff; display:flex; align-items:center; justify-content:center; font-weight:800; font-size:12px; flex-shrink:0; }
    .pdf-ex-info strong { display:block; font-size:13px; }
    .pdf-ex-info span { font-size:12px; color:#64748b; }
    @media print {
      body { padding:20px; }
      .no-print { display:none !important; }
    }
  </style>
</head>
<body>
  <div class="pdf-header">
    <h1>🏥 RehabAI — ${title}</h1>
    <div class="meta">
      Patient: ${App.profile?.full_name || 'Patient'}<br>
      Generated: ${new Date().toLocaleDateString('en-IN', { weekday:'long', year:'numeric', month:'long', day:'numeric' })}<br>
      Injury: ${(App.patientProfile?.injury_type || '').replace(/_/g,' ').replace(/\\b\\w/g, c=>c.toUpperCase()) || 'N/A'}
    </div>
  </div>
  ${bodyHtml}
  <div class="pdf-footer">
    This document was generated by RehabAI — Intelligent Rehabilitation Platform. For clinical decisions, always consult your physiotherapist or surgeon.
  </div>
  <div class="no-print" style="text-align:center;margin-top:24px;">
    <button onclick="window.print()" style="padding:12px 32px;background:#6366f1;color:#fff;border:none;border-radius:8px;font-size:14px;font-weight:700;cursor:pointer;">
      📥 Save as PDF / Print
    </button>
  </div>
</body>
</html>`);
    win.document.close();
    // Auto-trigger print after a brief delay for fonts to load
    setTimeout(() => win.print(), 800);
  },

  /** Build PDF content for the Medical Report Extractor */
  exportReport(data) {
    const d = data;
    const html = `
      <div class="pdf-section">
        <h2>📋 Extracted Clinical Details</h2>
        <div class="pdf-row"><span class="label">Diagnosis</span><span class="value">${d.diagnosis || '--'}</span></div>
        <div class="pdf-row"><span class="label">Surgery Details</span><span class="value">${d.surgery_details || '--'}</span></div>
        <div class="pdf-row"><span class="label">Follow-up Date</span><span class="value">${d.follow_up_date || '--'}</span></div>
        <div class="pdf-row"><span class="label">Medications</span><span class="value">${(d.medications || []).join(', ') || '--'}</span></div>
        <div class="pdf-row"><span class="label">Physio Instructions</span><span class="value">${d.physio_instructions || '--'}</span></div>
      </div>
      <div class="pdf-section">
        <h2>⚠️ Movement Restrictions</h2>
        ${(d.restrictions || []).map(r => `<div class="pdf-row"><span class="value">• ${r}</span></div>`).join('') || '<p>No specific restrictions noted.</p>'}
      </div>`;
    this.download('Medical Report Analysis', html);
  },

  /** Build PDF content for the Meal Planner */
  exportMealPlan(plan) {
    const totals = plan.daily_totals || {};
    const meals = plan.meals || [];
    const html = `
      <div class="pdf-section">
        <h2>🍽️ ${plan.plan_name || 'Personalized Meal Plan'}</h2>
        ${plan.tips ? `<p style="font-size:13px;color:#64748b;margin-bottom:12px;">💡 ${plan.tips}</p>` : ''}
        ${totals.calories ? `
        <div class="pdf-macros">
          <div class="pdf-macro" style="background:#eef2ff;color:#6366f1;">${totals.calories} kcal</div>
          <div class="pdf-macro" style="background:#fff1f2;color:#f43f5e;">${totals.protein}g protein</div>
          <div class="pdf-macro" style="background:#fffbeb;color:#f59e0b;">${totals.carbs}g carbs</div>
          <div class="pdf-macro" style="background:#ecfdf5;color:#10b981;">${totals.fat}g fat</div>
        </div>` : ''}
      </div>
      ${meals.map((meal, i) => `
        <div class="pdf-card">
          <h4>${['🌅','☀️','🌙','🍎'][i % 4]} ${(meal.type || 'Meal').toUpperCase()} — ${meal.name}</h4>
          <p style="font-size:12px;color:#64748b;margin-bottom:8px;">⏱ Prep: ${meal.prep_time || '15 mins'}</p>
          <h3>Ingredients</h3>
          <ul>${(meal.ingredients || []).map(ing => `<li>${ing}</li>`).join('')}</ul>
          <h3 style="margin-top:10px;">Instructions</h3>
          <ol>${(meal.instructions || []).map(step => `<li>${step}</li>`).join('')}</ol>
          ${meal.nutrition ? `
            <div class="pdf-macros">
              <div class="pdf-macro">${meal.nutrition.calories || 0} cal</div>
              <div class="pdf-macro">${meal.nutrition.protein || 0}g P</div>
              <div class="pdf-macro">${meal.nutrition.carbs || 0}g C</div>
              <div class="pdf-macro">${meal.nutrition.fat || 0}g F</div>
            </div>` : ''}
        </div>`).join('')}`;
    this.download('Recovery Meal Plan', html);
  },

  /** Build PDF content for the Voice Coach Workout Plan */
  exportWorkout(plan) {
    const exercises = plan.exercises || [];
    const html = `
      <div class="pdf-section">
        <h2>💪 ${plan.plan_name || 'Workout Plan'}</h2>
        <p style="font-size:13px;color:#64748b;margin-bottom:4px;">${plan.summary || ''}</p>
        <p style="font-size:13px;margin-bottom:12px;"><strong>Duration:</strong> ${plan.duration || '20 min'}</p>
      </div>
      <div class="pdf-section">
        <h2>🏋️ Exercises (${exercises.length})</h2>
        ${exercises.map((ex, i) => `
          <div class="pdf-exercise">
            <div class="pdf-ex-num">${i + 1}</div>
            <div class="pdf-ex-info">
              <strong>${ex.name}</strong>
              <span>${ex.sets} sets × ${ex.reps} reps</span>
              ${ex.notes ? `<span style="display:block;color:#f59e0b;font-size:11px;margin-top:2px;">⚠ ${ex.notes}</span>` : ''}
            </div>
          </div>`).join('')}
      </div>
      ${plan.cooldown ? `<div class="pdf-section"><h2>🧘 Cooldown</h2><p style="font-size:13px;">${plan.cooldown}</p></div>` : ''}
      ${plan.tips ? `<div class="pdf-section"><h2>💡 Tips</h2><p style="font-size:13px;">${plan.tips}</p></div>` : ''}`;
    this.download('Workout Plan', html);
  },
};
